### ISSUE TITLE
Refactor of scripts that need to be split up

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#150]
Loose file that need to be split up:
 - [x] `from addie.treelib import BraggTree` -> `addie.rietveld.braggtree.py` (72469b06e6eb4f8fe3456206abf4ba4825d27929)
 - [x] `from addie.treelib import GofRTree` -> `addie.calculate_gr.gofrtree.py` (186587a8ab5a2a43844fae3832b2e5756b827a2b)
 - [x] `from addie.graphicsviewlib import BraggView` -> `addie.rietveld.braggview.py` (16e7bbce42422dacf0b8873a8e21d62a79c46dab)
 - [x] `from addie.graphicsviewlib import GofRView` -> `addie.calculate_gr.gofrtree.py` (16e7bbce42422dacf0b8873a8e21d62a79c46dab)

We need to look closer at the following since may go away with other issues:
 - [x] `addie.addiedriver.py` - Definitely related to #144 (final refactoring of this one will be in a new ticket) (but some clean up done here 31985d267526bcb7131e4a660114f032899e3381)
 - [x] `addie.ipythondockwidget.py` - See #143
 - [x] `addie.mantid_ipython_widget.py` - See #143

And finally, a major refactor of `addie.addie` main script 

Refs #144

**Comment by JeanBilheux** [comment]
work will be done in a new branch called refactor_split_up

**Comment by JeanBilheux** [comment]
Fix flake8 (82b0a7c903b387e50cb393d6213fed105a0f8e3c)
